---
# playbook.yml
- name: 'Run post-provision ansible tasks'
  hosts: default
  vars:
    LOGDNA_KEY: "{{ LOGDNA_KEY }}"

  tasks:
    - name: Update yum packages 
      yum: name=* state=latest
      when: ansible_facts['os_family'] == "RedHat"    
    - name: Update apt packages
      apt: upgrade=yes update_cache=yes
      when: ansible_facts['os_family'] == "Debian"   
    - name: Update Arch packages
      pacman: upgrade=yes update_cache=yes
      when: ansible_facts['os_family'] == "Archlinux"  