---
# playbook.yml
- name: 'Update deployed machines'
  hosts: default
  tasks:
    - name: Update yum packages 
      yum: name=* state=latest
      when: ansible_facts['os_family'] == "RedHat"    
    - name: Update apt packages
      apt: upgrade=yes update_cache=yes
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10
      when: ansible_facts['os_family'] == "Debian"   
    - name: Update Arch packages
      pacman: upgrade=yes update_cache=yes
      when: ansible_facts['os_family'] == "Archlinux"  